version: 2
jobs:
  build:
    working_directory: /go/src/github.com/prasincs/logrotate-sync
    docker:
      - image: circle/golang:1.9.2
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS/go-test.out
